### ISSUE TITLE
disable ssl cert verification

### ISSUE THREAD

**Issue by ridhomard** [Greums/robotframework-websocketclient#7]
Any way to do this ? 
It seems unable to connect to `wss` in Travis

**Comment by greums** [comment]
ssl cert verification can be disabled at websocket creation, using `sslopt` option. Please refer to https://github.com/websocket-client/websocket-client#how-to-disable-ssl-cert-verification for more details.

Also consider setting correct cookies for wss connection, if any.

**Comment by ridhomard** [comment]
Hi thanks for reply , but i can't make it work . 

> *** Variables ***
> 
> ${myws}            wss://echo.websocket.org, sslopt={"cert_reqs": ssl.CERT_NONE})
> 
> 
> *** Keywords ***
> Connect to WS
> 
>    ${my_websocket}=    WebSocketClient.Connect    ${myws}
> 

It returned me an error `ValueError: invalid literal for int() with base 10: 'ssl.CERT_NONE})'`

Did i do something wrong ?

**Comment by greums** [comment]
Well, had to scratch my head on this one.

It seems websocket_client is expecting an integer as `sslopt` dictionary values. `ssl.CERT_NONE` is an enum constant, aka a shortcut for an named integer value, but RobotFramework dictionary doesn't cast `ssl.CERT_NONE` to this integer value. So we have to do it ourselves...

Now, `python -c 'import ssl; print(ssl.CERT_NONE)'` give us the enum value, which is 0.

Set a `sslopt` dictionary with expected enum value:

```robotframework
*** Settings ***
Library  WebSocketClient

*** Variables ***
${myws}  wss://echo.websocket.org

*** Test Cases ***
Connect to WS
    &{sslopt} =  Create Dictionary  cert_reqs  ${0}         
    ${my_websocket}=  WebSocketClient.Connect  ${myws}  sslopt=${sslopt}
```
and it works !

```bash
$ robot test.robot 
==============================================================================
Test                                                                          
==============================================================================
Connect to WS                                                         | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```

**Comment by ridhomard** [comment]
Nice , Thank you very much for this details explanation 👍  . And  yeah It works!! 🥇
